"""Generate a NoneBot2 plugin that embeds a configured MailFlow instance.

The generated package is a standard ``nonebot-plugin-mailflow`` wheel: a
``pyproject.toml`` (declaring ``nonebot2`` plus every enabled MailFlow
plugin as dependencies), the plugin module registering driver
startup/shutdown hooks, and the resolved ``config.toml``. Installing it into
a NoneBot project (``NONEBOT_PLUGINS`` or ``load_plugin``) boots the MailFlow
service together with the bot.

Secrets note: the embedded config is the *resolved* live configuration. If it
contains real tokens, replace them with ``${ENV_VAR}`` placeholders in the
generated ``config.toml`` before committing the plugin anywhere.
"""

from __future__ import annotations

from mailflow.bot_export import BotExportContext, BotExportResult
from mailflow.config import write_config

PLUGIN_NAME = "nonebot-plugin-mailflow"
MODULE_NAME = "nonebot_plugin_mailflow"
FRAMEWORK = "nonebot"

_PYPROJECT = """[project]
name = "{name}"
version = "{version}"
description = "MailFlow engine embedded in NoneBot2 (generated by mailflow export)"
requires-python = ">=3.11"
dependencies = [
    "nonebot2>=2.0.0",
    "mailflow-core",
    "mailflow-bundled",
{deps}
]

[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"

[tool.hatch.build.targets.wheel]
packages = ["src/{module}"]
"""

_PLUGIN_INIT = '''"""MailFlow engine embedded as a NoneBot2 plugin (generated by mailflow export).

Install this package into a NoneBot2 project and load it (add it to
``NONEBOT_PLUGINS`` or call ``load_plugin``); the MailFlow service starts
with the bot and stops on shutdown. Configure it by editing
``config.toml`` next to this module.

Chat commands are prefixed with ``mailflow`` (``mailflow mail list``,
``mailflow help``) so they never collide with other plugins\' commands.
Long replies and the daily digest are split into separate messages.
"""

from __future__ import annotations

from pathlib import Path
from typing import Any

from nonebot import get_driver, on_message

driver = get_driver()
_service: Any = None
_router: Any = None

_PAGE_CHARS = 3500
_PAGE_ROWS = 10


def _chunk(text: str, limit: int = _PAGE_CHARS) -> list[str]:
    """Split a reply into messages that stay under ``limit`` characters,
    preferring line boundaries (each row is one chat-friendly line)."""
    lines = text.splitlines() or [""]
    chunks: list[str] = []
    current = ""
    for line in lines:
        if current and len(current) + len(line) + 1 > limit:
            chunks.append(current)
            current = line
        else:
            current = f"{current}\\n{line}" if current else line
    if current:
        chunks.append(current)
    return chunks


@driver.on_startup
async def _start_mailflow() -> None:
    """Boot the MailFlow service and the command router when NoneBot starts."""
    global _service, _router
    if _service is not None:
        return
    from mailflow.commands import CommandRouter
    from mailflow.config import load_config
    from mailflow.service import start_service
    from mailflow_bundled import create_plugin_manager

    config = load_config(Path(__file__).resolve().parent / "config.toml")
    _service = await start_service(config, plugin_manager=create_plugin_manager(config))
    await _service.start()
    _router = CommandRouter(_service)
    _service.on("mailflow.action.digest", _send_digest)


@driver.on_shutdown
async def _stop_mailflow() -> None:
    """Stop the MailFlow service when NoneBot shuts down."""
    global _service, _router
    if _service is not None:
        await _service.stop()
        _service = None
        _router = None


_mailflow_matcher = on_message(priority=10, block=False)


@_mailflow_matcher.handle()
async def _handle_mailflow(event: Any) -> None:
    """Dispatch ``mailflow ...`` chat messages to the shared command router."""
    text = str(event.get_plaintext() or "").strip()
    if not text.startswith("mailflow ") or _router is None:
        return
    response = await _router.execute(text[len("mailflow "):].strip())
    for chunk in _chunk(response.text):
        await _mailflow_matcher.send(chunk)


async def _send_digest(event: str, **payload: Any) -> None:
    """Forward the daily digest as paginated chat messages."""
    items = payload.get("items") or []
    lines = [
        f"{i.due_at:%m-%d %H:%M} [{i.action_type}] {i.summary}"
        for i in items
    ]
    if not lines:
        return
    for page in range(0, len(lines), _PAGE_ROWS):
        block = lines[page : page + _PAGE_ROWS]
        await _mailflow_matcher.send(
            "\\n".join(block)
            + f"\\n— {payload.get('today_count', 0)} due today, "
            + f"{payload.get('upcoming_count', 0)} approaching —"
        )
'''

_README = """# {name}

MailFlow engine embedded as a NoneBot2 plugin, generated by
`mailflow export --framework nonebot`.

## Install

```bash
pip install {name}
```

Add `{name}` to `NONEBOT_PLUGINS` in your NoneBot project (or call
`load_plugin`), then edit `config.toml` inside
`src/{module}/` (after `pip show {name}`) to match your mailboxes, LLMs and
plugins. The MailFlow service starts together with the bot.

## Configuration

`config.toml` is the standard MailFlow configuration (see
`mailflow config list`). Replace any real secrets with `${{ENV_VAR}}`
placeholders before sharing the plugin.

## Notes

- Every enabled MailFlow plugin is declared as a dependency and discovered
  at startup; disable plugins through the MailFlow config `[plugins]`
  section instead of uninstalling packages.
- Chat commands are not part of this plugin; use the MailFlow CLI/TUI for
  management.
"""


def export_nonebot(context: BotExportContext) -> BotExportResult:
    """Write the NoneBot2 plugin package under ``context.output_dir``."""
    output = context.output_dir
    output.mkdir(parents=True, exist_ok=True)
    version = context.version or "0.1.0"
    deps = ",\n".join(f'    "{pid}",' for pid in sorted(set(context.plugin_ids)))
    (output / "pyproject.toml").write_text(
        _PYPROJECT.format(
            name=PLUGIN_NAME,
            version=version,
            module=MODULE_NAME,
            deps=deps,
        ),
        encoding="utf-8",
    )
    (output / "README.md").write_text(
        _README.format(name=PLUGIN_NAME, module=MODULE_NAME), encoding="utf-8"
    )
    module_dir = output / "src" / MODULE_NAME
    module_dir.mkdir(parents=True, exist_ok=True)
    (module_dir / "__init__.py").write_text(_PLUGIN_INIT, encoding="utf-8")
    write_config(context.config, module_dir / "config.toml")
    created = [
        "pyproject.toml",
        "README.md",
        f"src/{MODULE_NAME}/__init__.py",
        f"src/{MODULE_NAME}/config.toml",
    ]
    return BotExportResult(
        framework=FRAMEWORK,
        plugin_name=PLUGIN_NAME,
        created=created,
        notes=(
            "The exported config.toml contains the resolved live configuration; "
            "replace real secrets with ${ENV_VAR} placeholders before sharing."
        ),
    )


__all__ = ["export_nonebot"]
