"""Generate an AstrBot plugin that embeds a configured MailFlow instance.

The generated package is an AstrBot plugin folder (``main.py`` +
``metadata.yaml`` + ``config.toml`` + ``requirements.txt``): drop it into
AstrBot's ``plugins/`` directory (or install via the dashboard), and the
MailFlow service boots with the plugin lifecycle (``initialize`` /
``terminate``). AstrBot auto-installs the dependencies listed in
``requirements.txt``.

Secrets note: the embedded config is the *resolved* live configuration. If it
contains real tokens, replace them with ``${ENV_VAR}`` placeholders in the
generated ``config.toml`` before committing the plugin anywhere.
"""

from __future__ import annotations

from mailflow.bot_export import BotExportContext, BotExportResult
from mailflow.config import write_config

PLUGIN_NAME = "astrbot_plugin_mailflow"
FRAMEWORK = "astrbot"

_METADATA = """name: {name}
desc: MailFlow engine embedded in AstrBot (generated by mailflow export)
author: MailFlow
version: {version}
repo: https://github.com/Kingcxp/mailflow
"""

_MAIN = '''"""MailFlow engine embedded as an AstrBot plugin (generated by mailflow export).

Drop this folder into AstrBot\\'s ``plugins/`` directory (or install it from
the dashboard); the MailFlow service starts when the plugin is activated and
stops when it is disabled or reloaded. Configure it by editing
``config.toml`` next to this file.
"""

from __future__ import annotations

from pathlib import Path
from typing import Any

from astrbot.api.star import Context, Star

_service: Any = None


class Main(Star):
    """Boots and stops the MailFlow service with the AstrBot lifecycle."""

    def __init__(self, context: Context) -> None:
        super().__init__(context)

    async def initialize(self) -> None:
        """Called when the plugin is activated: start MailFlow."""
        global _service
        if _service is not None:
            return
        from mailflow.config import load_config
        from mailflow.service import start_service
        from mailflow_bundled import create_plugin_manager

        config = load_config(Path(__file__).resolve().parent / "config.toml")
        _service = await start_service(config, plugin_manager=create_plugin_manager(config))
        await _service.start()

    async def terminate(self) -> None:
        """Called when the plugin is disabled or reloaded: stop MailFlow."""
        global _service
        if _service is not None:
            await _service.stop()
            _service = None
'''

_README = """# {name}

MailFlow engine embedded as an AstrBot plugin, generated by
`mailflow export --framework astrbot`.

## Install

Copy this folder into AstrBot's `plugins/` directory (or install it from
the dashboard). AstrBot installs the dependencies from `requirements.txt`
and activates the plugin; the MailFlow service starts automatically.

## Configuration

`config.toml` is the standard MailFlow configuration (see
`mailflow config list`). Replace any real secrets with `${{ENV_VAR}}`
placeholders before sharing the plugin.

## Notes

- Every enabled MailFlow plugin is declared as a dependency and discovered
  at startup; disable plugins through the MailFlow config `[plugins]`
  section instead of removing packages.
- Chat commands are not part of this plugin; use the MailFlow CLI/TUI for
  management.
"""


def export_astrbot(context: BotExportContext) -> BotExportResult:
    """Write the AstrBot plugin package under ``context.output_dir``."""
    output = context.output_dir
    output.mkdir(parents=True, exist_ok=True)
    version = context.version or "0.1.0"
    (output / "metadata.yaml").write_text(
        _METADATA.format(name=PLUGIN_NAME, version=version), encoding="utf-8"
    )
    (output / "main.py").write_text(_MAIN, encoding="utf-8")
    (output / "README.md").write_text(_README.format(name=PLUGIN_NAME), encoding="utf-8")
    requirements = ["mailflow-core", "mailflow-bundled", *sorted(set(context.plugin_ids))]
    (output / "requirements.txt").write_text("\n".join(requirements) + "\n", encoding="utf-8")
    write_config(context.config, output / "config.toml")
    created = ["metadata.yaml", "main.py", "README.md", "requirements.txt", "config.toml"]
    return BotExportResult(
        framework=FRAMEWORK,
        plugin_name=PLUGIN_NAME,
        created=created,
        notes=(
            "The exported config.toml contains the resolved live configuration; "
            "replace real secrets with ${ENV_VAR} placeholders before sharing."
        ),
    )


__all__ = ["export_astrbot"]
